// src/lib/criminalCodeData.js
// Complete Criminal Code (RSC 1985, c C-46) section lookup.
// Auto-generated from Justice Laws XML (laws-lois.justice.gc.ca/eng/XML/C-46.xml)
// Generated: March 2026 | Sections: 490
// Includes all offence-creating sections + key definitional/duty sections.
//
// This file is used by api/verify.js to confirm AI-suggested Criminal Code
// sections are real. A section NOT in this table is not necessarily fake —
// it may be a valid procedural section we chose not to include.

const JUSTICE_LAWS_BASE = "https://laws-lois.justice.gc.ca/eng/acts/c-46";

export const CRIMINAL_CODE_SECTIONS = new Map([
  ["2", { title: "Definitions", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-2.html` }],
  ["7", { title: "Offences committed on aircraft", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-7.html` }],
  ["17", { title: "Compulsion by threats", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-17.html` }],
  ["18", { title: "Compulsion of spouse", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-18.html` }],
  ["19", { title: "Ignorance of the law", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-19.html` }],
  ["21", { title: "Parties to offence", severity: "", maxPenalty: "Same as principal offence", url: `${JUSTICE_LAWS_BASE}/section-21.html` }],
  ["22", { title: "Person counselling offence", severity: "", maxPenalty: "Same as principal offence", url: `${JUSTICE_LAWS_BASE}/section-22.html` }],
  ["22.1", { title: "Offences of negligence — organizations", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-22.1.html` }],
  ["22.2", { title: "Other offences — organizations", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-22.2.html` }],
  ["23", { title: "Accessory after the fact", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-23.html` }],
  ["24", { title: "Attempts", severity: "", maxPenalty: "See s. 463", url: `${JUSTICE_LAWS_BASE}/section-24.html` }],
  ["25", { title: "Protection of persons acting under authority", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-25.html` }],
  ["26", { title: "Excessive force", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-26.html` }],
  ["28", { title: "Arrest of wrong person", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-28.html` }],
  ["29", { title: "Duty of person arresting", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-29.html` }],
  ["30", { title: "Preventing breach of peace", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-30.html` }],
  ["31", { title: "Arrest for breach of peace", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-31.html` }],
  ["32", { title: "Use of force to suppress riot", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-32.html` }],
  ["33.1", { title: "Offences of violence by negligence", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-33.1.html` }],
  ["34", { title: "Defence — use or threat of force", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-34.html` }],
  ["35", { title: "Defence — property", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-35.html` }],
  ["43", { title: "Correction of child by force", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-43.html` }],
  ["46", { title: "High treason", severity: "Indictable", maxPenalty: "Life imprisonment (high treason)", url: `${JUSTICE_LAWS_BASE}/section-46.html` }],
  ["47", { title: "Punishment for high treason", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-47.html` }],
  ["50", { title: "Assisting alien enemy to leave Canada, or omitting to prevent treason", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-50.html` }],
  ["51", { title: "Intimidating Parliament or legislature", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-51.html` }],
  ["52", { title: "Sabotage", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-52.html` }],
  ["52.1", { title: "Sabotage — essential infrastructure", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-52.1.html` }],
  ["52.2", { title: "Sabotage — device", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-52.2.html` }],
  ["53", { title: "Inciting to mutiny", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-53.html` }],
  ["54", { title: "Assisting deserter", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-54.html` }],
  ["56", { title: "Offences in relation to members of R.C.M.P.", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-56.html` }],
  ["56.1", { title: "Identity documents", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-56.1.html` }],
  ["57", { title: "Forgery of or uttering forged passport", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-57.html` }],
  ["58", { title: "Fraudulent use of certificate of citizenship", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-58.html` }],
  ["61", { title: "Punishment of seditious offences", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-61.html` }],
  ["62", { title: "Offences in relation to military forces", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-62.html` }],
  ["65", { title: "Punishment of rioter", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-65.html` }],
  ["66", { title: "Punishment for unlawful assembly", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-66.html` }],
  ["67", { title: "Reading proclamation", severity: "", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-67.html` }],
  ["68", { title: "Offences related to proclamation", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-68.html` }],
  ["69", { title: "Neglect by peace officer", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-69.html` }],
  ["70", { title: "Orders by Governor in Council", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-70.html` }],
  ["73", { title: "Punishment", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-73.html` }],
  ["74", { title: "Piracy by law of nations", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-74.html` }],
  ["75", { title: "Piratical acts", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-75.html` }],
  ["76", { title: "Hijacking", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-76.html` }],
  ["77", { title: "Endangering safety of aircraft or airport", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-77.html` }],
  ["78", { title: "Offensive weapons and explosive substances", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-78.html` }],
  ["78.1", { title: "Seizing control of ship or fixed platform", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-78.1.html` }],
  ["79", { title: "Duty of care re explosive", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-79.html` }],
  ["80", { title: "Breach of duty", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-80.html` }],
  ["81", { title: "Using explosives", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-81.html` }],
  ["82", { title: "Possession of explosive", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-82.html` }],
  ["82.3", { title: "Possession, etc., of nuclear material, radioactive material or device", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-82.3.html` }],
  ["82.4", { title: "Use or alteration of nuclear material, radioactive material or device", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-82.4.html` }],
  ["82.5", { title: "Commission of indictable offence to obtain nuclear material, etc.", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-82.5.html` }],
  ["82.6", { title: "Threats", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-82.6.html` }],
  ["83", { title: "Engaging in prize fight", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-83.html` }],
  ["83.02", { title: "Providing or collecting property for certain activities", severity: "Indictable", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-83.02.html` }],
  ["83.2", { title: "Commission of offence for terrorist group", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-83.2.html` }],
  ["83.03", { title: "Providing, making available, etc., property or services for terrorist purposes", severity: "Indictable", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-83.03.html` }],
  ["83.04", { title: "Using or possessing property for terrorist purposes", severity: "Indictable", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-83.04.html` }],
  ["83.12", { title: "Offences — freezing of property, disclosure or audit", severity: "Summary", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-83.12.html` }],
  ["83.18", { title: "Participation in activity of terrorist group", severity: "Indictable", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-83.18.html` }],
  ["83.19", { title: "Facilitating terrorist activity", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-83.19.html` }],
  ["83.21", { title: "Instructing to carry out activity for terrorist group", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-83.21.html` }],
  ["83.22", { title: "Instructing to carry out terrorist activity", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-83.22.html` }],
  ["83.23", { title: "Concealing person who carried out terrorist activity", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-83.23.html` }],
  ["83.27", { title: "Punishment for terrorist activity", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-83.27.html` }],
  ["83.181", { title: "Leaving Canada to participate in activity of terrorist group", severity: "Indictable", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-83.181.html` }],
  ["83.191", { title: "Leaving Canada to facilitate terrorist activity", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-83.191.html` }],
  ["83.201", { title: "Leaving Canada to commit offence for terrorist group", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-83.201.html` }],
  ["83.202", { title: "Leaving Canada to commit offence that is terrorist activity", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-83.202.html` }],
  ["83.221", { title: "Counselling commission of terrorism offence", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-83.221.html` }],
  ["83.231", { title: "Hoax — terrorist activity", severity: "Hybrid", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-83.231.html` }],
  ["85", { title: "Using firearm in commission of offence", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-85.html` }],
  ["86", { title: "Careless use of firearm, etc.", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-86.html` }],
  ["87", { title: "Pointing a firearm", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-87.html` }],
  ["88", { title: "Possession of weapon for dangerous purpose", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-88.html` }],
  ["89", { title: "Carrying weapon while attending public meeting", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-89.html` }],
  ["90", { title: "Carrying concealed weapon", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-90.html` }],
  ["91", { title: "Unauthorized possession of firearm", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-91.html` }],
  ["92", { title: "Possession of firearm knowing its possession is unauthorized", severity: "Indictable", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-92.html` }],
  ["93", { title: "Possession at unauthorized place", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-93.html` }],
  ["94", { title: "Unauthorized possession in motor vehicle", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-94.html` }],
  ["95", { title: "Possession of prohibited or restricted firearm with ammunition", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-95.html` }],
  ["96", { title: "Possession of weapon obtained by commission of offence", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-96.html` }],
  ["98", { title: "Breaking and entering to steal firearm", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-98.html` }],
  ["98.1", { title: "Robbery to steal firearm", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-98.1.html` }],
  ["99", { title: "Weapons trafficking", severity: "Indictable", maxPenalty: "14 years (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-99.html` }],
  ["100", { title: "Possession for purpose of weapons trafficking", severity: "Indictable", maxPenalty: "14 years (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-100.html` }],
  ["101", { title: "Transfer without authority", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-101.html` }],
  ["102", { title: "Making automatic firearm", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-102.html` }],
  ["102.1", { title: "Possession of computer data", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-102.1.html` }],
  ["103", { title: "Importing or exporting knowing it is unauthorized", severity: "Indictable", maxPenalty: "14 years (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-103.html` }],
  ["104", { title: "Unauthorized importing or exporting", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-104.html` }],
  ["104.1", { title: "Altering cartridge magazine", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-104.1.html` }],
  ["105", { title: "Losing or finding", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-105.html` }],
  ["106", { title: "Destroying", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-106.html` }],
  ["107", { title: "False statements", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-107.html` }],
  ["108", { title: "Tampering with serial number", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-108.html` }],
  ["117.01", { title: "Possession contrary to order", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-117.01.html` }],
  ["117.07", { title: "Public officers", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-117.07.html` }],
  ["117.08", { title: "Individuals acting for police force, Canadian Forces and visiting forces", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-117.08.html` }],
  ["117.09", { title: "Employees of business with licence", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-117.09.html` }],
  ["117.14", { title: "Amnesty period", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-117.14.html` }],
  ["117.071", { title: "Preclearance officers", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-117.071.html` }],
  ["119", { title: "Bribery of judicial officers, etc.", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-119.html` }],
  ["120", { title: "Bribery of officers", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-120.html` }],
  ["121", { title: "Frauds on the government", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-121.html` }],
  ["121.1", { title: "Selling, etc., of tobacco products and raw leaf tobacco", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-121.1.html` }],
  ["122", { title: "Breach of trust by public officer", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-122.html` }],
  ["123", { title: "Municipal corruption", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-123.html` }],
  ["124", { title: "Selling or purchasing office", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-124.html` }],
  ["125", { title: "Influencing or negotiating appointments or dealing in offices", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-125.html` }],
  ["126", { title: "Disobeying a statute", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-126.html` }],
  ["127", { title: "Disobeying order of court", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-127.html` }],
  ["128", { title: "Misconduct of officers executing process", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-128.html` }],
  ["129", { title: "Offences relating to public or peace officer", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-129.html` }],
  ["130", { title: "Personating peace officer", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-130.html` }],
  ["131", { title: "Perjury", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-131.html` }],
  ["132", { title: "Punishment", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-132.html` }],
  ["134", { title: "Idem", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-134.html` }],
  ["136", { title: "Witness giving contradictory evidence", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-136.html` }],
  ["137", { title: "Fabricating evidence", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-137.html` }],
  ["138", { title: "Offences relating to affidavits", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-138.html` }],
  ["139", { title: "Obstructing justice", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-139.html` }],
  ["140", { title: "Public mischief", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-140.html` }],
  ["141", { title: "Compounding indictable offence", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-141.html` }],
  ["142", { title: "Corruptly taking reward for recovery of goods", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-142.html` }],
  ["144", { title: "Prison breach", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-144.html` }],
  ["145", { title: "Escape and being at large without excuse", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-145.html` }],
  ["146", { title: "Permitting or assisting escape", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-146.html` }],
  ["147", { title: "Rescue or permitting escape", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-147.html` }],
  ["148", { title: "Assisting prisoner of war to escape", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-148.html` }],
  ["150.1", { title: "Consent no defence", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-150.1.html` }],
  ["151", { title: "Sexual interference", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-151.html` }],
  ["152", { title: "Invitation to sexual touching", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-152.html` }],
  ["153", { title: "Sexual exploitation", severity: "Hybrid", maxPenalty: "14 years (minimum 16 years)", url: `${JUSTICE_LAWS_BASE}/section-153.html` }],
  ["153.1", { title: "Sexual exploitation of person with disability", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-153.1.html` }],
  ["155", { title: "Incest", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-155.html` }],
  ["160", { title: "Bestiality", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-160.html` }],
  ["161", { title: "Order of prohibition", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-161.html` }],
  ["162", { title: "Voyeurism", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-162.html` }],
  ["162.1", { title: "Publication, etc., of an intimate image without consent", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-162.1.html` }],
  ["162.2", { title: "Prohibition order", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-162.2.html` }],
  ["163", { title: "Obscene materials", severity: "Hybrid", maxPenalty: "2 years indictable", url: `${JUSTICE_LAWS_BASE}/section-163.html` }],
  ["163.1", { title: "Definition of", severity: "Hybrid", maxPenalty: "14 years (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-163.1.html` }],
  ["167", { title: "Immoral theatrical performance", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-167.html` }],
  ["168", { title: "Mailing obscene matter", severity: "Hybrid", maxPenalty: "2 years indictable", url: `${JUSTICE_LAWS_BASE}/section-168.html` }],
  ["169", { title: "Punishment", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-169.html` }],
  ["170", { title: "Parent or guardian procuring sexual activity", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-170.html` }],
  ["171", { title: "Householder permitting prohibited sexual activity", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-171.html` }],
  ["171.1", { title: "Making sexually explicit material available to child", severity: "Hybrid", maxPenalty: "14 years (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-171.1.html` }],
  ["172", { title: "Corrupting children", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-172.html` }],
  ["172.1", { title: "Luring a child", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-172.1.html` }],
  ["172.2", { title: "Agreement or arrangement — sexual offence against child", severity: "Hybrid", maxPenalty: "14 years (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-172.2.html` }],
  ["173", { title: "Indecent acts", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-173.html` }],
  ["174", { title: "Nudity", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-174.html` }],
  ["175", { title: "Causing disturbance, indecent exhibition, loitering, etc.", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-175.html` }],
  ["176", { title: "Obstructing or violence to or arrest of officiating clergyman", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-176.html` }],
  ["177", { title: "Trespassing at night", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-177.html` }],
  ["180", { title: "Common nuisance", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-180.html` }],
  ["182", { title: "Dead body", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-182.html` }],
  ["184", { title: "Interception", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-184.html` }],
  ["184.5", { title: "Interception of radio-based telephone communications", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-184.5.html` }],
  ["191", { title: "Possession, etc.", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-191.html` }],
  ["193", { title: "Disclosure of information", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-193.html` }],
  ["193.1", { title: "Disclosure of information received from interception of radio-based telephone communications", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-193.1.html` }],
  ["197", { title: "Definitions", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-197.html` }],
  ["201", { title: "Keeping gaming or betting house", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-201.html` }],
  ["202", { title: "Betting, pool-selling, book-making, etc.", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-202.html` }],
  ["203", { title: "Placing bets on behalf of others", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-203.html` }],
  ["204", { title: "Exemption", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-204.html` }],
  ["206", { title: "Offence in relation to lotteries and games of chance", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-206.html` }],
  ["207", { title: "Permitted lotteries", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-207.html` }],
  ["207.1", { title: "Exemption — lottery scheme on an international cruise ship", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-207.1.html` }],
  ["209", { title: "Cheating at play", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-209.html` }],
  ["213", { title: "Stopping or impeding traffic", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-213.html` }],
  ["214", { title: "Definitions", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-214.html` }],
  ["215", { title: "Duty of persons to provide necessaries", severity: "Hybrid", maxPenalty: "5 years indictable / 2 years summary", url: `${JUSTICE_LAWS_BASE}/section-215.html` }],
  ["216", { title: "Duty of persons undertaking acts dangerous to life", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-216.html` }],
  ["217", { title: "Duty of persons undertaking acts", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-217.html` }],
  ["217.1", { title: "Duty of persons directing work", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-217.1.html` }],
  ["218", { title: "Abandoning child", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-218.html` }],
  ["219", { title: "Criminal negligence", severity: "", maxPenalty: "See s. 220-221", url: `${JUSTICE_LAWS_BASE}/section-219.html` }],
  ["220", { title: "Causing death by criminal negligence", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-220.html` }],
  ["221", { title: "Causing bodily harm by criminal negligence", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-221.html` }],
  ["222", { title: "Homicide", severity: "", maxPenalty: "See s. 229-240", url: `${JUSTICE_LAWS_BASE}/section-222.html` }],
  ["223", { title: "When child becomes human being", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-223.html` }],
  ["224", { title: "Death that might have been prevented", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-224.html` }],
  ["225", { title: "Death from treatment of injury", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-225.html` }],
  ["226", { title: "Acceleration of death", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-226.html` }],
  ["227", { title: "Exemption for medical assistance in dying", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-227.html` }],
  ["228", { title: "Killing by influence on the mind", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-228.html` }],
  ["229", { title: "Murder", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-229.html` }],
  ["231", { title: "Classification of murder", severity: "Indictable", maxPenalty: "Life imprisonment (minimum 25 years 1st degree)", url: `${JUSTICE_LAWS_BASE}/section-231.html` }],
  ["232", { title: "Murder reduced to manslaughter", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-232.html` }],
  ["233", { title: "Infanticide", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-233.html` }],
  ["234", { title: "Manslaughter", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-234.html` }],
  ["235", { title: "Punishment for murder", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-235.html` }],
  ["236", { title: "Manslaughter", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-236.html` }],
  ["237", { title: "Punishment for infanticide", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-237.html` }],
  ["238", { title: "Killing unborn child in act of birth", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-238.html` }],
  ["239", { title: "Attempt to commit murder", severity: "Indictable", maxPenalty: "Life imprisonment (minimum 10 years)", url: `${JUSTICE_LAWS_BASE}/section-239.html` }],
  ["240", { title: "Accessory after fact to murder", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-240.html` }],
  ["240.1", { title: "Removal without informed consent", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-240.1.html` }],
  ["241", { title: "Counselling or aiding suicide", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-241.html` }],
  ["241.3", { title: "Failure to comply with safeguards", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-241.3.html` }],
  ["241.4", { title: "Forgery", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-241.4.html` }],
  ["241.31", { title: "Filing information — practitioners", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-241.31.html` }],
  ["242", { title: "Neglect to obtain assistance in childbirth", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-242.html` }],
  ["243", { title: "Concealing body of child", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-243.html` }],
  ["244", { title: "Discharging firearm with intent", severity: "Indictable", maxPenalty: "14 years (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-244.html` }],
  ["244.1", { title: "Causing bodily harm with intent — air gun or pistol", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-244.1.html` }],
  ["244.2", { title: "Discharging firearm — recklessness", severity: "Indictable", maxPenalty: "14 years (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-244.2.html` }],
  ["245", { title: "Administering noxious thing", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-245.html` }],
  ["246", { title: "Overcoming resistance to commission of offence", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-246.html` }],
  ["247", { title: "Traps likely to cause bodily harm", severity: "Hybrid", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-247.html` }],
  ["248", { title: "Interfering with transportation facilities", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-248.html` }],
  ["262", { title: "Impeding attempt to save life", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-262.html` }],
  ["263", { title: "Duty to safeguard opening in ice", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-263.html` }],
  ["264", { title: "Criminal harassment", severity: "Hybrid", maxPenalty: "10 years indictable", url: `${JUSTICE_LAWS_BASE}/section-264.html` }],
  ["264.1", { title: "Uttering threats", severity: "Hybrid", maxPenalty: "5 years indictable", url: `${JUSTICE_LAWS_BASE}/section-264.1.html` }],
  ["265", { title: "Assault", severity: "Hybrid", maxPenalty: "See s. 266-268", url: `${JUSTICE_LAWS_BASE}/section-265.html` }],
  ["266", { title: "Assault", severity: "Hybrid", maxPenalty: "5 years indictable / 2 years summary", url: `${JUSTICE_LAWS_BASE}/section-266.html` }],
  ["267", { title: "Assault with a weapon or causing bodily harm", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-267.html` }],
  ["268", { title: "Aggravated assault", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-268.html` }],
  ["269", { title: "Unlawfully causing bodily harm", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-269.html` }],
  ["269.1", { title: "Torture", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-269.1.html` }],
  ["270", { title: "Assaulting a peace officer", severity: "Hybrid", maxPenalty: "5 years indictable", url: `${JUSTICE_LAWS_BASE}/section-270.html` }],
  ["270.01", { title: "Assaulting peace officer with weapon or causing bodily harm", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-270.01.html` }],
  ["270.1", { title: "Disarming a peace officer", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-270.1.html` }],
  ["270.02", { title: "Aggravated assault of peace officer", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-270.02.html` }],
  ["271", { title: "Sexual assault", severity: "Hybrid", maxPenalty: "14 years (minimum 16 years)", url: `${JUSTICE_LAWS_BASE}/section-271.html` }],
  ["272", { title: "Sexual assault with a weapon, threats to a third party or causing bodily harm", severity: "Indictable", maxPenalty: "Life imprisonment (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-272.html` }],
  ["273", { title: "Aggravated sexual assault", severity: "Indictable", maxPenalty: "Life imprisonment (minimum 16 years)", url: `${JUSTICE_LAWS_BASE}/section-273.html` }],
  ["273.1", { title: "Meaning of", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-273.1.html` }],
  ["273.2", { title: "Where belief in consent not a defence", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-273.2.html` }],
  ["273.3", { title: "Removal of child from Canada", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-273.3.html` }],
  ["278.9", { title: "Publication prohibited", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-278.9.html` }],
  ["278.95", { title: "Publication prohibited", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-278.95.html` }],
  ["279", { title: "Kidnapping", severity: "Hybrid", maxPenalty: "Life imprisonment (minimum 16 years)", url: `${JUSTICE_LAWS_BASE}/section-279.html` }],
  ["279.01", { title: "Trafficking in persons", severity: "Indictable", maxPenalty: "Life imprisonment (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-279.01.html` }],
  ["279.1", { title: "Hostage taking", severity: "Indictable", maxPenalty: "Life imprisonment (minimum 10 years)", url: `${JUSTICE_LAWS_BASE}/section-279.1.html` }],
  ["279.02", { title: "Material benefit — trafficking", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-279.02.html` }],
  ["279.03", { title: "Withholding or destroying documents — trafficking", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-279.03.html` }],
  ["279.011", { title: "Trafficking of a person under the age of eighteen years", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-279.011.html` }],
  ["280", { title: "Abduction of person under age of 16", severity: "Hybrid", maxPenalty: "5 years indictable", url: `${JUSTICE_LAWS_BASE}/section-280.html` }],
  ["281", { title: "Abduction of person under age of 14", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-281.html` }],
  ["282", { title: "Abduction in contravention of custody or parenting order", severity: "Hybrid", maxPenalty: "10 years indictable", url: `${JUSTICE_LAWS_BASE}/section-282.html` }],
  ["283", { title: "Abduction", severity: "Hybrid", maxPenalty: "10 years indictable", url: `${JUSTICE_LAWS_BASE}/section-283.html` }],
  ["284", { title: "Defence", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-284.html` }],
  ["285", { title: "Defence", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-285.html` }],
  ["286.1", { title: "Obtaining sexual services for consideration", severity: "Hybrid", maxPenalty: "10 years (minimum 18 years)", url: `${JUSTICE_LAWS_BASE}/section-286.1.html` }],
  ["286.2", { title: "Material benefit from sexual services", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-286.2.html` }],
  ["286.3", { title: "Procuring", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-286.3.html` }],
  ["286.4", { title: "Advertising sexual services", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-286.4.html` }],
  ["291", { title: "Punishment", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-291.html` }],
  ["292", { title: "Procuring feigned marriage", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-292.html` }],
  ["293", { title: "Polygamy", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-293.html` }],
  ["293.1", { title: "Forced marriage", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-293.1.html` }],
  ["293.2", { title: "Marriage under age of 16 years", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-293.2.html` }],
  ["294", { title: "Pretending to solemnize marriage", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-294.html` }],
  ["295", { title: "Marriage contrary to law", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-295.html` }],
  ["300", { title: "Punishment of libel known to be false", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-300.html` }],
  ["301", { title: "Punishment for defamatory libel", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-301.html` }],
  ["302", { title: "Extortion by libel", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-302.html` }],
  ["318", { title: "Advocating genocide", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-318.html` }],
  ["319", { title: "Public incitement of hatred", severity: "Hybrid", maxPenalty: "2 years indictable", url: `${JUSTICE_LAWS_BASE}/section-319.html` }],
  ["320.2", { title: "Punishment in case of bodily harm", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-320.2.html` }],
  ["320.13", { title: "Dangerous operation", severity: "Hybrid", maxPenalty: "10 years / life if death", url: `${JUSTICE_LAWS_BASE}/section-320.13.html` }],
  ["320.14", { title: "Operation while impaired", severity: "Hybrid", maxPenalty: "10 years / life if death", url: `${JUSTICE_LAWS_BASE}/section-320.14.html` }],
  ["320.15", { title: "Failure or refusal to comply with demand", severity: "Hybrid", maxPenalty: "10 years / life if death", url: `${JUSTICE_LAWS_BASE}/section-320.15.html` }],
  ["320.16", { title: "Failure to stop after accident", severity: "Hybrid", maxPenalty: "10 years / life if death", url: `${JUSTICE_LAWS_BASE}/section-320.16.html` }],
  ["320.17", { title: "Flight from peace officer", severity: "Hybrid", maxPenalty: "10 years / life if death", url: `${JUSTICE_LAWS_BASE}/section-320.17.html` }],
  ["320.18", { title: "Operation while prohibited", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-320.18.html` }],
  ["320.19", { title: "Punishment", severity: "Hybrid", maxPenalty: "10 years (minimum 10 years)", url: `${JUSTICE_LAWS_BASE}/section-320.19.html` }],
  ["320.21", { title: "Punishment in case of death", severity: "", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-320.21.html` }],
  ["320.23", { title: "Delay of sentencing", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-320.23.html` }],
  ["320.24", { title: "Mandatory prohibition order", severity: "", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-320.24.html` }],
  ["320.36", { title: "Unauthorized use of bodily substance", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-320.36.html` }],
  ["320.37", { title: "Refusal to take sample", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-320.37.html` }],
  ["320.102", { title: "Conversion therapy", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-320.102.html` }],
  ["320.103", { title: "Promoting or advertising", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-320.103.html` }],
  ["320.104", { title: "Material benefit", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-320.104.html` }],
  ["322", { title: "Theft", severity: "", maxPenalty: "See s. 334", url: `${JUSTICE_LAWS_BASE}/section-322.html` }],
  ["324", { title: "Theft by bailee of things under seizure", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-324.html` }],
  ["327", { title: "Possession of device to obtain use of telecommunication facility or service", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-327.html` }],
  ["333.1", { title: "Motor vehicle theft", severity: "Hybrid", maxPenalty: "10 years (minimum 14 years)", url: `${JUSTICE_LAWS_BASE}/section-333.1.html` }],
  ["333.2", { title: "Possession of device for purpose of committing theft", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-333.2.html` }],
  ["334", { title: "Punishment for theft", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-334.html` }],
  ["335", { title: "Taking motor vehicle or vessel or found therein without consent", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-335.html` }],
  ["336", { title: "Criminal breach of trust", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-336.html` }],
  ["338", { title: "Fraudulently taking cattle or defacing brand", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-338.html` }],
  ["339", { title: "Taking possession, etc., of drift timber", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-339.html` }],
  ["340", { title: "Destroying documents of title", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-340.html` }],
  ["341", { title: "Fraudulent concealment", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-341.html` }],
  ["342", { title: "Theft, forgery, etc., of credit card", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-342.html` }],
  ["342.01", { title: "Instruments for copying credit card data or forging or falsifying credit cards", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-342.01.html` }],
  ["342.1", { title: "Unauthorized use of computer", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-342.1.html` }],
  ["342.2", { title: "Possession of device to obtain unauthorized use of computer system or to commit mischief", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-342.2.html` }],
  ["343", { title: "Robbery", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-343.html` }],
  ["344", { title: "Robbery", severity: "Indictable", maxPenalty: "Life imprisonment (minimum 10 years)", url: `${JUSTICE_LAWS_BASE}/section-344.html` }],
  ["345", { title: "Stopping mail with intent", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-345.html` }],
  ["346", { title: "Extortion", severity: "Indictable", maxPenalty: "Life imprisonment (minimum 10 years)", url: `${JUSTICE_LAWS_BASE}/section-346.html` }],
  ["347", { title: "Criminal interest rate", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-347.html` }],
  ["348", { title: "Breaking and entering with intent, committing offence or breaking out", severity: "Hybrid", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-348.html` }],
  ["349", { title: "Being unlawfully in dwelling-house", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-349.html` }],
  ["351", { title: "Possession of break-in instrument", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-351.html` }],
  ["352", { title: "Possession of instruments for breaking into coin-operated or currency exchange devices", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-352.html` }],
  ["353", { title: "Selling, etc., automobile master key", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-353.html` }],
  ["353.1", { title: "Tampering with vehicle identification number", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-353.1.html` }],
  ["354", { title: "Possession of property obtained by crime", severity: "Hybrid", maxPenalty: "10 years (over $5,000) / 2 years (under)", url: `${JUSTICE_LAWS_BASE}/section-354.html` }],
  ["355", { title: "Punishment", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-355.html` }],
  ["355.2", { title: "Trafficking in property obtained by crime", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-355.2.html` }],
  ["355.4", { title: "Possession of property obtained by crime — trafficking", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-355.4.html` }],
  ["355.5", { title: "Punishment", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-355.5.html` }],
  ["356", { title: "Theft from mail", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-356.html` }],
  ["357", { title: "Bringing into Canada property obtained by crime", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-357.html` }],
  ["362", { title: "False pretence or false statement", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-362.html` }],
  ["363", { title: "Obtaining execution of valuable security by fraud", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-363.html` }],
  ["364", { title: "Fraudulently obtaining food, beverage or accommodation", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-364.html` }],
  ["366", { title: "Forgery", severity: "Indictable", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-366.html` }],
  ["367", { title: "Punishment for forgery", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-367.html` }],
  ["368", { title: "Use, trafficking or possession of forged document", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-368.html` }],
  ["368.1", { title: "Forgery instruments", severity: "Hybrid", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-368.1.html` }],
  ["368.2", { title: "Public officers acting in the course of their duties or employment", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-368.2.html` }],
  ["369", { title: "Exchequer bill paper, public seals, etc.", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-369.html` }],
  ["372", { title: "False information", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-372.html` }],
  ["374", { title: "Drawing document without authority, etc.", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-374.html` }],
  ["375", { title: "Obtaining, etc., by instrument based on forged document", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-375.html` }],
  ["376", { title: "Counterfeiting stamp, etc.", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-376.html` }],
  ["377", { title: "Damaging documents", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-377.html` }],
  ["378", { title: "Offences in relation to registers", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-378.html` }],
  ["380", { title: "Fraud", severity: "Hybrid", maxPenalty: "14 years (over $5,000) / 2 years (under)", url: `${JUSTICE_LAWS_BASE}/section-380.html` }],
  ["380.2", { title: "Prohibition order", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-380.2.html` }],
  ["381", { title: "Using mails to defraud", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-381.html` }],
  ["382", { title: "Fraudulent manipulation of stock exchange transactions", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-382.html` }],
  ["382.1", { title: "Prohibited insider trading", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-382.1.html` }],
  ["383", { title: "Gaming in stocks or merchandise", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-383.html` }],
  ["384", { title: "Broker reducing stock by selling for their own account", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-384.html` }],
  ["385", { title: "Fraudulent concealment of title documents", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-385.html` }],
  ["386", { title: "Fraudulent registration of title", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-386.html` }],
  ["387", { title: "Fraudulent sale of real property", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-387.html` }],
  ["388", { title: "Misleading receipt", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-388.html` }],
  ["389", { title: "Fraudulent disposal of goods on which money advanced", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-389.html` }],
  ["390", { title: "Fraudulent receipts under", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-390.html` }],
  ["391", { title: "Trade secret", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-391.html` }],
  ["392", { title: "Disposal of property to defraud creditors", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-392.html` }],
  ["393", { title: "Fraud in relation to fares, etc.", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-393.html` }],
  ["394", { title: "Fraud in relation to valuable minerals", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-394.html` }],
  ["394.1", { title: "Possession of stolen or fraudulently obtained valuable minerals", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-394.1.html` }],
  ["396", { title: "Offences in relation to mines", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-396.html` }],
  ["397", { title: "Books and documents", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-397.html` }],
  ["398", { title: "Falsifying employment record", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-398.html` }],
  ["399", { title: "False return by public officer", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-399.html` }],
  ["400", { title: "False prospectus, etc.", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-400.html` }],
  ["401", { title: "Obtaining carriage by false billing", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-401.html` }],
  ["402.2", { title: "Identity theft", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-402.2.html` }],
  ["403", { title: "Identity fraud", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-403.html` }],
  ["405", { title: "Acknowledging instrument in false name", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-405.html` }],
  ["407", { title: "Offence", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-407.html` }],
  ["408", { title: "Passing off", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-408.html` }],
  ["409", { title: "Instruments for forging trademark", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-409.html` }],
  ["410", { title: "Other offences in relation to trademarks", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-410.html` }],
  ["411", { title: "Used goods sold without disclosure", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-411.html` }],
  ["412", { title: "Punishment", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-412.html` }],
  ["415", { title: "Offences in relation to wreck", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-415.html` }],
  ["417", { title: "Applying or removing marks without authority", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-417.html` }],
  ["418", { title: "Selling defective stores to Her Majesty", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-418.html` }],
  ["419", { title: "Unlawful use of military uniforms or certificates", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-419.html` }],
  ["420", { title: "Military stores", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-420.html` }],
  ["422", { title: "Criminal breach of contract", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-422.html` }],
  ["423", { title: "Intimidation", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-423.html` }],
  ["423.1", { title: "Intimidation of a justice system participant or a journalist", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-423.1.html` }],
  ["423.2", { title: "Intimidation — health services", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-423.2.html` }],
  ["424", { title: "Threat against internationally protected person", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-424.html` }],
  ["424.1", { title: "Threat against United Nations or associated personnel", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-424.1.html` }],
  ["425", { title: "Offences by employers", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-425.html` }],
  ["425.1", { title: "Threats and retaliation against employees", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-425.1.html` }],
  ["426", { title: "Secret commissions", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-426.html` }],
  ["429", { title: "Wilfully causing event to occur", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-429.html` }],
  ["430", { title: "Mischief", severity: "Hybrid", maxPenalty: "Life imprisonment (minimum 10 years)", url: `${JUSTICE_LAWS_BASE}/section-430.html` }],
  ["431", { title: "Attack on premises, residence or transport of internationally protected person", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-431.html` }],
  ["431.1", { title: "Attack on premises, accommodation or transport of United Nations or associated personnel", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-431.1.html` }],
  ["431.2", { title: "Definitions", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-431.2.html` }],
  ["432", { title: "Unauthorized recording of a movie", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-432.html` }],
  ["433", { title: "Arson — disregard for human life", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-433.html` }],
  ["434", { title: "Arson — damage to property", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-434.html` }],
  ["434.1", { title: "Arson — own property", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-434.1.html` }],
  ["435", { title: "Arson for fraudulent purpose", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-435.html` }],
  ["436", { title: "Arson by negligence", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-436.html` }],
  ["436.1", { title: "Possession of incendiary material", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-436.1.html` }],
  ["437", { title: "False alarm of fire", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-437.html` }],
  ["438", { title: "Interfering with saving of wrecked vessel", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-438.html` }],
  ["439", { title: "Interfering with marine signal, etc.", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-439.html` }],
  ["440", { title: "Removing natural bar without permission", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-440.html` }],
  ["441", { title: "Occupant injuring building", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-441.html` }],
  ["442", { title: "Interfering with boundary lines", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-442.html` }],
  ["443", { title: "Interfering with international boundary marks, etc.", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-443.html` }],
  ["445", { title: "Injuring or endangering other animals", severity: "Hybrid", maxPenalty: "5 years indictable", url: `${JUSTICE_LAWS_BASE}/section-445.html` }],
  ["445.01", { title: "Killing or injuring certain animals", severity: "Hybrid", maxPenalty: "5 years indictable", url: `${JUSTICE_LAWS_BASE}/section-445.01.html` }],
  ["445.1", { title: "Causing unnecessary suffering", severity: "Hybrid", maxPenalty: "5 years indictable / 18 months summary", url: `${JUSTICE_LAWS_BASE}/section-445.1.html` }],
  ["445.2", { title: "Definition of", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-445.2.html` }],
  ["446", { title: "Causing damage or injury", severity: "Hybrid", maxPenalty: "5 years indictable", url: `${JUSTICE_LAWS_BASE}/section-446.html` }],
  ["447", { title: "Arena for animal fighting", severity: "Hybrid", maxPenalty: "5 years indictable", url: `${JUSTICE_LAWS_BASE}/section-447.html` }],
  ["447.1", { title: "Order of prohibition or restitution", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-447.1.html` }],
  ["449", { title: "Making", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-449.html` }],
  ["450", { title: "Possession, etc., of counterfeit money", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-450.html` }],
  ["451", { title: "Having clippings, etc.", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-451.html` }],
  ["452", { title: "Uttering, etc., counterfeit money", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-452.html` }],
  ["453", { title: "Uttering coin", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-453.html` }],
  ["454", { title: "Slugs and tokens", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-454.html` }],
  ["455", { title: "Clipping and uttering clipped coin", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-455.html` }],
  ["456", { title: "Defacing current coins", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-456.html` }],
  ["457", { title: "Likeness of bank-notes", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-457.html` }],
  ["458", { title: "Making, having or dealing in instruments for counterfeiting", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-458.html` }],
  ["459", { title: "Conveying instruments for coining out of mint", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-459.html` }],
  ["460", { title: "Advertising and dealing in counterfeit money, etc.", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-460.html` }],
  ["462.31", { title: "Laundering proceeds of crime", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-462.31.html` }],
  ["462.32", { title: "Special search warrant", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-462.32.html` }],
  ["462.33", { title: "Application for restraint order", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-462.33.html` }],
  ["462.321", { title: "Special warrant — digital assets", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-462.321.html` }],
  ["462.371", { title: "Definition of", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-462.371.html` }],
  ["463", { title: "Attempts, accessories", severity: "Hybrid", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-463.html` }],
  ["464", { title: "Counselling offence that is not committed", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-464.html` }],
  ["465", { title: "Conspiracy", severity: "Hybrid", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-465.html` }],
  ["467.11", { title: "Participation in activities of criminal organization", severity: "Hybrid", maxPenalty: "5 years", url: `${JUSTICE_LAWS_BASE}/section-467.11.html` }],
  ["467.12", { title: "Commission of offence for criminal organization", severity: "Indictable", maxPenalty: "14 years", url: `${JUSTICE_LAWS_BASE}/section-467.12.html` }],
  ["467.13", { title: "Instructing commission of offence for criminal organization", severity: "Indictable", maxPenalty: "Life imprisonment", url: `${JUSTICE_LAWS_BASE}/section-467.13.html` }],
  ["467.111", { title: "Recruitment of members by a criminal organization", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-467.111.html` }],
  ["477.1", { title: "Offences outside of Canada", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-477.1.html` }],
  ["486.6", { title: "Offence", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-486.6.html` }],
  ["487", { title: "Information for search warrant", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-487.html` }],
  ["487.2", { title: "Restriction on publication", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-487.2.html` }],
  ["487.08", { title: "Use of bodily substances — warrant", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-487.08.html` }],
  ["487.0197", { title: "Offence — preservation demand", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-487.0197.html` }],
  ["487.0198", { title: "Offence — preservation or production order", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-487.0198.html` }],
  ["487.0199", { title: "Offence — destruction of preserved data", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-487.0199.html` }],
  ["487.0552", { title: "Failure to comply with order or summons", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-487.0552.html` }],
  ["489", { title: "Seizure of things not specified", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-489.html` }],
  ["490.8", { title: "Application for restraint order", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-490.8.html` }],
  ["490.031", { title: "Offence", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-490.031.html` }],
  ["490.0311", { title: "Offence", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-490.0311.html` }],
  ["490.0312", { title: "Offence", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-490.0312.html` }],
  ["492", { title: "Seizure of explosives", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-492.html` }],
  ["495", { title: "Arrest without warrant by peace officer", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-495.html` }],
  ["497", { title: "Issue of appearance notice by peace officer", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-497.html` }],
  ["517", { title: "Order directing matters not to be published for specified period", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-517.html` }],
  ["539", { title: "Order restricting publication of evidence taken at preliminary inquiry", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-539.html` }],
  ["542", { title: "Confession or admission of accused", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-542.html` }],
  ["570", { title: "Record of conviction or order", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-570.html` }],
  ["605", { title: "Release of exhibits for testing", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-605.html` }],
  ["648", { title: "Restriction on publication", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-648.html` }],
  ["649", { title: "Disclosure of jury proceedings", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-649.html` }],
  ["662", { title: "Offence charged, part only proved", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-662.html` }],
  ["669.1", { title: "Jurisdiction", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-669.1.html` }],
  ["672.25", { title: "Postponing trial of issue", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-672.25.html` }],
  ["672.37", { title: "Definition of", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-672.37.html` }],
  ["672.501", { title: "Order restricting publication — sexual offences", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-672.501.html` }],
  ["708", { title: "Contempt", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-708.html` }],
  ["718", { title: "Purpose", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-718.html` }],
  ["718.1", { title: "Fundamental principle", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-718.1.html` }],
  ["718.2", { title: "Other sentencing principles", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-718.2.html` }],
  ["718.21", { title: "Additional factors", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-718.21.html` }],
  ["721", { title: "Report by probation officer", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-721.html` }],
  ["730", { title: "Conditional and absolute discharge", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-730.html` }],
  ["732.11", { title: "Prohibition on use of bodily substance", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-732.11.html` }],
  ["733.1", { title: "Failure to comply with probation order", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-733.1.html` }],
  ["742.1", { title: "Imposing of conditional sentence", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-742.1.html` }],
  ["742.31", { title: "Prohibition on use of bodily substance", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-742.31.html` }],
  ["743", { title: "Imprisonment when no other provision", severity: "Indictable", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-743.html` }],
  ["743.21", { title: "Non-communication order", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-743.21.html` }],
  ["753.3", { title: "Breach of long-term supervision", severity: "Hybrid", maxPenalty: "10 years", url: `${JUSTICE_LAWS_BASE}/section-753.3.html` }],
  ["785", { title: "Definitions", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-785.html` }],
  ["787", { title: "General penalty", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-787.html` }],
  ["801", { title: "Arraignment", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-801.html` }],
  ["809", { title: "Costs", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-809.html` }],
  ["810", { title: "If injury or damage feared", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-810.html` }],
  ["810.01", { title: "Fear of certain offences", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-810.01.html` }],
  ["810.1", { title: "Where fear of sexual offence", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-810.1.html` }],
  ["810.02", { title: "Fear of forced marriage or marriage under age of 16 years", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-810.02.html` }],
  ["810.2", { title: "Where fear of serious personal injury offence", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-810.2.html` }],
  ["810.4", { title: "Prohibition on use of bodily substance", severity: "Summary", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-810.4.html` }],
  ["810.5", { title: "Orders under sections 486 to 486.5 and 486.7", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-810.5.html` }],
  ["810.011", { title: "Fear of terrorism offence", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-810.011.html` }],
  ["811", { title: "Breach of recognizance", severity: "Hybrid", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-811.html` }],
  ["836", { title: "Appeal under section 830", severity: "", maxPenalty: "", url: `${JUSTICE_LAWS_BASE}/section-836.html` }],
]);

/**
 * Normalize a citation string like "s. 348(1)(b)" to its base section number "348".
 * Handles decimal sections like "s. 320.14(1)(a)" → "320.14".
 * Returns null if the string does not look like a Criminal Code section.
 */
export function normalizeSection(citation) {
  if (!citation || typeof citation !== "string") return null;
  const match = citation.match(/(?:^s\.\s*|^section\s+|^)(\d+(?:\.\d+)?)/i);
  return match ? match[1] : null;
}

/**
 * Look up a Criminal Code section. Returns the entry object or null.
 * Entry: { title, severity, maxPenalty, url }
 */
export function lookupSection(citation) {
  const num = normalizeSection(citation);
  if (!num) return null;
  return CRIMINAL_CODE_SECTIONS.get(num) || null;
}