// src/lib/criminalCodeParts.js
// Extracted from criminalCodeData.js to avoid pulling the full 316KB dataset
// into components that only need the parts list.
export const CRIMINAL_CODE_PARTS = [
  { id: "I", label: "Part I — General" },
  { id: "II", label: "Part II — Offences Against Public Order" },
  { id: "II.1", label: "Part II.1 — Terrorism" },
  { id: "III", label: "Part III — Firearms and Other Weapons" },
  { id: "IV", label: "Part IV — Offences Against Administration of Law and Justice" },
  { id: "V", label: "Part V — Sexual Offences, Public Morals and Disorderly Conduct" },
  { id: "VI", label: "Part VI — Invasion of Privacy" },
  { id: "VII", label: "Part VII — Disorderly Houses, Gaming and Betting" },
  { id: "VIII", label: "Part VIII — Offences Against the Person and Reputation" },
  { id: "VIII.1", label: "Part VIII.1 — Offences Relating to Conveyances" },
  { id: "IX", label: "Part IX — Offences Against Rights of Property" },
  { id: "X", label: "Part X — Fraudulent Transactions Relating to Contracts and Trade" },
  { id: "XI", label: "Part XI — Wilful and Forbidden Acts in Respect of Certain Property" },
  { id: "XII", label: "Part XII — Offences Relating to Currency" },
  { id: "XII.2", label: "Part XII.2 — Proceeds of Crime" },
  { id: "XIII", label: "Part XIII — Attempts — Conspiracies — Accessories" },
  { id: "XIV", label: "Part XIV — Jurisdiction" },
  { id: "XV", label: "Part XV — Special Procedure and Powers" },
  { id: "XVI", label: "Part XVI — Compelling Appearance and Interim Release" },
  { id: "XVII", label: "Part XVII — Language of Accused" },
  { id: "XVIII", label: "Part XVIII — Procedure on Preliminary Inquiry" },
  { id: "XVIII.1", label: "Part XVIII.1 — Case Management Judge" },
  { id: "XIX", label: "Part XIX — Indictable Offences — Trial Without Jury" },
  { id: "XIX.1", label: "Part XIX.1 — Nunavut Court of Justice" },
  { id: "XX", label: "Part XX — Procedure in Jury Trials and General Provisions" },
  { id: "XX.1", label: "Part XX.1 — Mental Disorder" },
  { id: "XXI", label: "Part XXI — Appeals — Indictable Offences" },
  { id: "XXI.1", label: "Part XXI.1 — Applications for Ministerial Review — Miscarriages of Justice" },
  { id: "XXII", label: "Part XXII — Procuring Attendance" },
  { id: "XXII.01", label: "Part XXII.01 — Remote Attendance by Certain Persons" },
  { id: "XXII.1", label: "Part XXII.1 — Remediation Agreements" },
  { id: "XXIII", label: "Part XXIII — Sentencing" },
  { id: "XXIV", label: "Part XXIV — Dangerous Offenders and Long-Term Offenders" },
  { id: "XXV", label: "Part XXV — Effect and Enforcement of Recognizances" },
  { id: "XXVI", label: "Part XXVI — Extraordinary Remedies" },
  { id: "XXVII", label: "Part XXVII — Summary Convictions" },
  { id: "XXVIII", label: "Part XXVIII — Miscellaneous" },
];
