export const RETRIEVAL_FAILURE_SET = [
  {
    id: "stolen_chair_not_socan",
    scenario: "My chair was stolen from outside my apartment.",
    expectedPrimary: "theft",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["SOCAN", "copyright", "royalty", "digital", "conversion"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "SOCAN v. Entertainment Software Association, 2022 SCC 30",
        title: "SOCAN v. Entertainment Software Association",
        ratio: "Copyright royalties and making works available online.",
        tags: ["copyright", "royalty", "digital", "property"],
        topics: ["intellectual property", "copyright"],
        year: 2022,
      },
    ],
  },
  {
    id: "robbery_positive_control",
    scenario: "A person threatened me and took my wallet by force near a bus stop.",
    expectedPrimary: "robbery",
    expectedResult: "nonzero_required",
    shouldInclude: ["robbery", "s. 343"],
    shouldExclude: ["R v Jordan", "11(b)", "trial delay"],
    expectedKeywords: ["robbery", "threat", "force"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v McCraw, [1991] 3 SCR 72",
        title: "R v McCraw",
        ratio: "Robbery analysis focuses on force or threats used to take property under s. 343.",
        tags: ["robbery", "s. 343", "violence", "threat"],
        topics: ["robbery", "force", "property"],
        year: 1991,
      },
    ],
  },
  {
    id: "search_positive_hunter",
    scenario: "Police searched my phone without a warrant after they stopped me.",
    expectedPrimary: "charter_search_seizure",
    expectedResult: "nonzero_required",
    shouldInclude: ["Hunter", "search"],
    shouldExclude: ["R v Jordan", "11(b)", "trial delay"],
    expectedKeywords: ["search", "seizure", "warrant"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Foundational Charter s. 8 case requiring prior authorization for most searches.",
        tags: ["charter", "s. 8", "search", "warrant"],
        topics: ["search", "seizure", "privacy"],
        year: 1984,
      },
    ],
  },
  {
    id: "delay_positive_jordan",
    scenario: "My trial has been delayed for over three years and keeps getting adjourned.",
    expectedPrimary: "trial_delay",
    expectedResult: "nonzero_required",
    shouldInclude: ["Jordan", "11(b)"],
    shouldExclude: ["Hunter v Southam", "R. v. Woods"],
    expectedKeywords: ["delay", "11(b)", "reasonable time"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Sets Charter section 11(b) ceilings for unreasonable trial delay.",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "theft_positive_control",
    scenario: "I am accused of shoplifting from a grocery store.",
    expectedPrimary: "theft",
    expectedResult: "nonzero_required",
    shouldInclude: ["theft", "s. 322"],
    shouldExclude: ["R v Jordan", "11(b)"],
    expectedKeywords: ["theft", "property", "dishonesty"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Stewart, [1988] 1 SCR 963",
        title: "R v Stewart",
        ratio: "Theft requires dishonest taking or conversion of property under s. 322.",
        tags: ["theft", "s. 322", "dishonesty", "property"],
        topics: ["theft", "property", "consent"],
        year: 1988,
      },
    ],
  },
  {
    id: "mugging_not_jordan",
    scenario: "I was mugged for $50 while walking home.",
    expectedPrimary: "robbery",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Jordan", "R. v. Jordan", "R v Cody", "11(b)", "trial delay"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Sets trial delay ceilings under Charter section 11(b)",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "search_not_jordan",
    scenario: "Police took my phone and searched messages without a warrant.",
    expectedPrimary: "charter_search_seizure",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Jordan", "R v Cody", "11(b)", "trial delay"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Trial delay case under Charter section 11(b).",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "robbery_not_hunter",
    scenario: "Someone robbed me and took my cash while threatening me.",
    expectedPrimary: "robbery",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Hunter v Southam", "search", "warrant"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Search and seizure framework under Charter s. 8.",
        tags: ["charter", "s. 8", "search", "warrant"],
        topics: ["search", "seizure", "privacy"],
        year: 1984,
      },
    ],
  },
  {
    id: "counsel_not_oakes",
    scenario: "I was detained and denied access to a lawyer for two hours.",
    expectedPrimary: "charter_counsel",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Oakes", "section 1", "proportionality"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Oakes, [1986] 1 SCR 103",
        title: "R v Oakes",
        ratio: "Section 1 proportionality test for Charter limits.",
        tags: ["charter", "section 1", "proportionality"],
        topics: ["charter", "section 1", "rights limits"],
        year: 1986,
      },
    ],
  },
  {
    id: "traffic_minor_hape",
    scenario: "I was pulled over for going 1 km/h over the speed limit. What case law applies?",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Hape", "R v Grant", "R v Oakes"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Hape, 2007 SCC 26",
        title: "R v Hape",
        ratio: "Extraterritorial application of the Charter",
        tags: ["charter", "foreign investigations", "extraterritoriality"],
        topics: ["Charter rights", "procedure"],
        year: 2007,
      },
    ],
  },
  {
    id: "traffic_minor_grant",
    scenario: "Routine speeding stop. I got a ticket but there was no search or arrest.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Grant", "Hunter v Southam", "R v Marakah"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Grant, 2009 SCC 32",
        title: "R v Grant",
        ratio: "Charter detention and exclusion analysis",
        tags: ["charter", "detention", "exclusion"],
        topics: ["Charter rights", "evidence"],
        year: 2009,
      },
    ],
  },
  {
    id: "traffic_minor_oakes",
    scenario: "I was stopped for a tiny speed overage and want to know if an old SCC landmark applies.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Oakes", "R. v. Woods"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Oakes, 1986 SCC 30",
        title: "R v Oakes",
        ratio: "Section 1 proportionality test",
        tags: ["charter", "section 1", "proportionality"],
        topics: ["Charter rights", "constitutional law"],
        year: 1986,
      },
    ],
  },
  {
    id: "robbery_bus_knife_positive",
    scenario: "Someone pulled a knife on me and took my phone at a bus platform.",
    expectedPrimary: "robbery",
    expectedResult: "nonzero_required",
    shouldInclude: ["robbery", "threat"],
    shouldExclude: ["Jordan", "11(b)", "trial delay"],
    expectedKeywords: ["robbery", "threat", "force"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v McCraw, [1991] 3 SCR 72",
        title: "R v McCraw",
        ratio: "Robbery analysis focuses on force or threats used to take property under s. 343.",
        tags: ["robbery", "s. 343", "violence", "threat"],
        topics: ["robbery", "force", "property"],
        year: 1991,
      },
    ],
  },
  {
    id: "theft_backpack_positive",
    scenario: "Security says I stole a backpack from a department store.",
    expectedPrimary: "theft",
    expectedResult: "nonzero_required",
    shouldInclude: ["theft", "property"],
    shouldExclude: ["Jordan", "11(b)"],
    expectedKeywords: ["theft", "property", "dishonesty"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Stewart, [1988] 1 SCR 963",
        title: "R v Stewart",
        ratio: "Theft requires dishonest taking or conversion of property under s. 322.",
        tags: ["theft", "s. 322", "dishonesty", "property"],
        topics: ["theft", "property", "consent"],
        year: 1988,
      },
    ],
  },
  {
    id: "search_home_warrant_positive",
    scenario: "Officers entered my home and searched my computer without a warrant.",
    expectedPrimary: "charter_search_seizure",
    expectedResult: "nonzero_required",
    shouldInclude: ["search", "warrant"],
    shouldExclude: ["Jordan", "11(b)", "trial delay"],
    expectedKeywords: ["search", "seizure", "warrant"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Foundational Charter s. 8 case requiring prior authorization for most searches.",
        tags: ["charter", "s. 8", "search", "warrant"],
        topics: ["search", "seizure", "privacy"],
        year: 1984,
      },
    ],
  },
  {
    id: "trial_delay_four_year_positive",
    scenario: "My criminal trial delay is over four years with repeated adjournments.",
    expectedPrimary: "trial_delay",
    expectedResult: "nonzero_required",
    shouldInclude: ["Jordan", "11(b)"],
    shouldExclude: ["Hunter v Southam", "R. v. Woods"],
    expectedKeywords: ["delay", "11(b)", "reasonable time"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Sets Charter section 11(b) ceilings for unreasonable trial delay.",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "roadside_counsel_variant_positive",
    scenario: "At a roadside detention they kept questioning me and would not let me call counsel.",
    expectedPrimary: "charter_counsel",
    expectedResult: "nonzero_required",
    shouldInclude: ["counsel", "roadside"],
    shouldExclude: ["Hape", "extraterritorial"],
    expectedKeywords: ["s. 10", "counsel", "detention"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside breath-demand contexts",
        tags: ["charter", "right to counsel", "roadside detention"],
        topics: ["Charter rights", "breath demand"],
        year: 2005,
      },
    ],
  },
  {
    id: "traffic_ticket_only_zero",
    scenario: "I got a simple speeding ticket and there was no detention, search, or arrest.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Grant", "Hunter", "Jordan"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Grant, 2009 SCC 32",
        title: "R v Grant",
        ratio: "Charter detention and exclusion analysis",
        tags: ["charter", "detention", "exclusion"],
        topics: ["Charter rights", "evidence"],
        year: 2009,
      },
    ],
  },
  {
    id: "camera_ticket_zero",
    scenario: "A speed camera mailed me a ticket. No officer stopped me and there was no search.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Grant", "Hunter", "Woods"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside breath-demand contexts",
        tags: ["charter", "right to counsel", "roadside detention"],
        topics: ["Charter rights", "breath demand"],
        year: 2005,
      },
    ],
  },
  {
    id: "neighbor_noise_zero",
    scenario: "My neighbor keeps blasting loud music late at night and I want legal options.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Jordan", "Hunter", "McCraw"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Sets trial delay ceilings under Charter section 11(b)",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "landlord_deposit_zero",
    scenario: "My landlord will not return my rent deposit and I want to know what to file.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Jordan", "Grant", "Oakes"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Oakes, [1986] 1 SCR 103",
        title: "R v Oakes",
        ratio: "Section 1 proportionality test for Charter limits.",
        tags: ["charter", "section 1", "proportionality"],
        topics: ["charter", "section 1", "rights limits"],
        year: 1986,
      },
    ],
  },
  {
    id: "peace_bond_neighbor_zero",
    scenario: "My ex keeps showing up outside my building. I want to know if I can get a peace bond.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Jordan", "Hunter", "Woods"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Search and seizure framework under Charter s. 8.",
        tags: ["charter", "s. 8", "search", "warrant"],
        topics: ["search", "seizure", "privacy"],
        year: 1984,
      },
    ],
  },
  {
    id: "jaywalking_ticket_zero",
    scenario: "I got a jaywalking ticket downtown. There was no search, detention, or force.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Grant", "Jordan", "McCraw"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v McCraw, [1991] 3 SCR 72",
        title: "R v McCraw",
        ratio: "Robbery analysis focuses on force or threats used to take property under s. 343.",
        tags: ["robbery", "s. 343", "violence", "threat"],
        topics: ["robbery", "force", "property"],
        year: 1991,
      },
    ],
  },
  {
    id: "lost_wallet_zero",
    scenario: "I lost my wallet on the subway and I am wondering what legal process applies.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Jordan", "Hunter", "Woods"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside breath-demand contexts",
        tags: ["charter", "right to counsel", "roadside detention"],
        topics: ["Charter rights", "breath demand"],
        year: 2005,
      },
    ],
  },
  {
    id: "roadside_counsel_positive_control",
    scenario: "I was detained at a roadside stop and couldn't call a lawyer for hours.",
    expectedPrimary: "charter_counsel",
    expectedResult: "nonzero_required",
    shouldInclude: ["Woods", "counsel"],
    shouldExclude: ["R v Hape"],
    expectedKeywords: ["s. 10", "counsel", "informational"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside breath-demand contexts",
        tags: ["charter", "right to counsel", "roadside detention"],
        topics: ["Charter rights", "breath demand"],
        year: 2005,
      },
    ],
  },
];