export const RETRIEVAL_FAILURE_SET = [
  {
    id: "stolen_chair_not_socan",
    scenario: "My chair was stolen from outside my apartment.",
    expectedPrimary: "theft",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["SOCAN", "copyright", "royalty", "digital", "conversion"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "SOCAN v. Entertainment Software Association, 2022 SCC 30",
        title: "SOCAN v. Entertainment Software Association",
        ratio: "Copyright royalties and making works available online.",
        tags: ["copyright", "royalty", "digital", "property"],
        topics: ["intellectual property", "copyright"],
        year: 2022,
      },
    ],
  },
  {
    id: "robbery_positive_control",
    scenario: "A person threatened me and took my wallet by force near a bus stop.",
    expectedPrimary: "robbery",
    expectedResult: "nonzero_required",
    shouldInclude: ["robbery", "s. 343"],
    shouldExclude: ["R v Jordan", "11(b)", "trial delay"],
    expectedKeywords: ["robbery", "threat", "force"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v McCraw, [1991] 3 SCR 72",
        title: "R v McCraw",
        ratio: "Robbery analysis focuses on force or threats used to take property under s. 343.",
        tags: ["robbery", "s. 343", "violence", "threat"],
        topics: ["robbery", "force", "property"],
        year: 1991,
      },
    ],
  },
  {
    id: "search_positive_hunter",
    scenario: "Police searched my phone without a warrant after they stopped me.",
    expectedPrimary: "charter_search_seizure",
    expectedResult: "nonzero_required",
    shouldInclude: ["Hunter", "search"],
    shouldExclude: ["R v Jordan", "11(b)", "trial delay"],
    expectedKeywords: ["search", "seizure", "warrant"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Foundational Charter s. 8 case requiring prior authorization for most searches.",
        tags: ["charter", "s. 8", "search", "warrant"],
        topics: ["search", "seizure", "privacy"],
        year: 1984,
      },
    ],
  },
  {
    id: "delay_positive_jordan",
    scenario: "My trial has been delayed for over three years and keeps getting adjourned.",
    expectedPrimary: "trial_delay",
    expectedResult: "nonzero_required",
    shouldInclude: ["Jordan", "11(b)"],
    shouldExclude: ["Hunter v Southam", "R. v. Woods"],
    expectedKeywords: ["delay", "11(b)", "reasonable time"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Sets Charter section 11(b) ceilings for unreasonable trial delay.",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "theft_positive_control",
    scenario: "I am accused of shoplifting from a grocery store.",
    expectedPrimary: "theft",
    expectedResult: "nonzero_required",
    shouldInclude: ["theft", "s. 322"],
    shouldExclude: ["R v Jordan", "11(b)"],
    expectedKeywords: ["theft", "property", "dishonesty"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Stewart, [1988] 1 SCR 963",
        title: "R v Stewart",
        ratio: "Theft requires dishonest taking or conversion of property under s. 322.",
        tags: ["theft", "s. 322", "dishonesty", "property"],
        topics: ["theft", "property", "consent"],
        year: 1988,
      },
    ],
  },
  {
    id: "mugging_not_jordan",
    scenario: "I was mugged for $50 while walking home.",
    expectedPrimary: "robbery",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Jordan", "R. v. Jordan", "R v Cody", "11(b)", "trial delay"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Sets trial delay ceilings under Charter section 11(b)",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "search_not_jordan",
    scenario: "Police took my phone and searched messages without a warrant.",
    expectedPrimary: "charter_search_seizure",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Jordan", "R v Cody", "11(b)", "trial delay"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Trial delay case under Charter section 11(b).",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "robbery_not_hunter",
    scenario: "Someone robbed me and took my cash while threatening me.",
    expectedPrimary: "robbery",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Hunter v Southam", "search", "warrant"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Search and seizure framework under Charter s. 8.",
        tags: ["charter", "s. 8", "search", "warrant"],
        topics: ["search", "seizure", "privacy"],
        year: 1984,
      },
    ],
  },
  {
    id: "counsel_not_oakes",
    scenario: "I was detained and denied access to a lawyer for two hours.",
    expectedPrimary: "charter_counsel",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Oakes", "section 1", "proportionality"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Oakes, [1986] 1 SCR 103",
        title: "R v Oakes",
        ratio: "Section 1 proportionality test for Charter limits.",
        tags: ["charter", "section 1", "proportionality"],
        topics: ["charter", "section 1", "rights limits"],
        year: 1986,
      },
    ],
  },
  {
    id: "traffic_minor_hape",
    scenario: "I was pulled over for going 1 km/h over the speed limit. What case law applies?",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Hape", "R v Grant", "R v Oakes"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Hape, 2007 SCC 26",
        title: "R v Hape",
        ratio: "Extraterritorial application of the Charter",
        tags: ["charter", "foreign investigations", "extraterritoriality"],
        topics: ["Charter rights", "procedure"],
        year: 2007,
      },
    ],
  },
  {
    id: "traffic_minor_grant",
    scenario: "Routine speeding stop. I got a ticket but there was no search or arrest.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Grant", "Hunter v Southam", "R v Marakah"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Grant, 2009 SCC 32",
        title: "R v Grant",
        ratio: "Charter detention and exclusion analysis",
        tags: ["charter", "detention", "exclusion"],
        topics: ["Charter rights", "evidence"],
        year: 2009,
      },
    ],
  },
  {
    id: "traffic_minor_oakes",
    scenario: "I was stopped for a tiny speed overage and want to know if an old SCC landmark applies.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["R v Oakes", "R. v. Woods"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Oakes, 1986 SCC 30",
        title: "R v Oakes",
        ratio: "Section 1 proportionality test",
        tags: ["charter", "section 1", "proportionality"],
        topics: ["Charter rights", "constitutional law"],
        year: 1986,
      },
    ],
  },
  {
    id: "robbery_bus_knife_positive",
    scenario: "Someone pulled a knife on me and took my phone at a bus platform.",
    expectedPrimary: "robbery",
    expectedResult: "nonzero_required",
    shouldInclude: ["robbery", "threat"],
    shouldExclude: ["Jordan", "11(b)", "trial delay"],
    expectedKeywords: ["robbery", "threat", "force"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v McCraw, [1991] 3 SCR 72",
        title: "R v McCraw",
        ratio: "Robbery analysis focuses on force or threats used to take property under s. 343.",
        tags: ["robbery", "s. 343", "violence", "threat"],
        topics: ["robbery", "force", "property"],
        year: 1991,
      },
    ],
  },
  {
    id: "theft_backpack_positive",
    scenario: "Security says I stole a backpack from a department store.",
    expectedPrimary: "theft",
    expectedResult: "nonzero_required",
    shouldInclude: ["theft", "property"],
    shouldExclude: ["Jordan", "11(b)"],
    expectedKeywords: ["theft", "property", "dishonesty"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Stewart, [1988] 1 SCR 963",
        title: "R v Stewart",
        ratio: "Theft requires dishonest taking or conversion of property under s. 322.",
        tags: ["theft", "s. 322", "dishonesty", "property"],
        topics: ["theft", "property", "consent"],
        year: 1988,
      },
    ],
  },
  {
    id: "search_home_warrant_positive",
    scenario: "Officers entered my home and searched my computer without a warrant.",
    expectedPrimary: "charter_search_seizure",
    expectedResult: "nonzero_required",
    shouldInclude: ["search", "warrant"],
    shouldExclude: ["Jordan", "11(b)", "trial delay"],
    expectedKeywords: ["search", "seizure", "warrant"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Foundational Charter s. 8 case requiring prior authorization for most searches.",
        tags: ["charter", "s. 8", "search", "warrant"],
        topics: ["search", "seizure", "privacy"],
        year: 1984,
      },
    ],
  },
  {
    id: "trial_delay_four_year_positive",
    scenario: "My criminal trial delay is over four years with repeated adjournments.",
    expectedPrimary: "trial_delay",
    expectedResult: "nonzero_required",
    shouldInclude: ["Jordan", "11(b)"],
    shouldExclude: ["Hunter v Southam", "R. v. Woods"],
    expectedKeywords: ["delay", "11(b)", "reasonable time"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Sets Charter section 11(b) ceilings for unreasonable trial delay.",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "roadside_counsel_variant_positive",
    scenario: "At a roadside detention they kept questioning me and would not let me call counsel.",
    expectedPrimary: "charter_counsel",
    expectedResult: "nonzero_required",
    shouldInclude: ["counsel", "roadside"],
    shouldExclude: ["Hape", "extraterritorial"],
    expectedKeywords: ["s. 10", "counsel", "detention"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside breath-demand contexts",
        tags: ["charter", "right to counsel", "roadside detention"],
        topics: ["Charter rights", "breath demand"],
        year: 2005,
      },
    ],
  },
  {
    id: "traffic_ticket_only_zero",
    scenario: "I got a simple speeding ticket and there was no detention, search, or arrest.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Grant", "Hunter", "Jordan"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Grant, 2009 SCC 32",
        title: "R v Grant",
        ratio: "Charter detention and exclusion analysis",
        tags: ["charter", "detention", "exclusion"],
        topics: ["Charter rights", "evidence"],
        year: 2009,
      },
    ],
  },
  {
    id: "camera_ticket_zero",
    scenario: "A speed camera mailed me a ticket. No officer stopped me and there was no search.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Grant", "Hunter", "Woods"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside breath-demand contexts",
        tags: ["charter", "right to counsel", "roadside detention"],
        topics: ["Charter rights", "breath demand"],
        year: 2005,
      },
    ],
  },
  {
    id: "neighbor_noise_zero",
    scenario: "My neighbor keeps blasting loud music late at night and I want legal options.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Jordan", "Hunter", "McCraw"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Sets trial delay ceilings under Charter section 11(b)",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "landlord_deposit_zero",
    scenario: "My landlord will not return my rent deposit and I want to know what to file.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Jordan", "Grant", "Oakes"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Oakes, [1986] 1 SCR 103",
        title: "R v Oakes",
        ratio: "Section 1 proportionality test for Charter limits.",
        tags: ["charter", "section 1", "proportionality"],
        topics: ["charter", "section 1", "rights limits"],
        year: 1986,
      },
    ],
  },
  {
    id: "peace_bond_neighbor_zero",
    scenario: "My ex keeps showing up outside my building. I want to know if I can get a peace bond.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Jordan", "Hunter", "Woods"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Search and seizure framework under Charter s. 8.",
        tags: ["charter", "s. 8", "search", "warrant"],
        topics: ["search", "seizure", "privacy"],
        year: 1984,
      },
    ],
  },
  {
    id: "jaywalking_ticket_zero",
    scenario: "I got a jaywalking ticket downtown. There was no search, detention, or force.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Grant", "Jordan", "McCraw"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v McCraw, [1991] 3 SCR 72",
        title: "R v McCraw",
        ratio: "Robbery analysis focuses on force or threats used to take property under s. 343.",
        tags: ["robbery", "s. 343", "violence", "threat"],
        topics: ["robbery", "force", "property"],
        year: 1991,
      },
    ],
  },
  {
    id: "lost_wallet_zero",
    scenario: "I lost my wallet on the subway and I am wondering what legal process applies.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Jordan", "Hunter", "Woods"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside breath-demand contexts",
        tags: ["charter", "right to counsel", "roadside detention"],
        topics: ["Charter rights", "breath demand"],
        year: 2005,
      },
    ],
  },
  {
    id: "roadside_counsel_positive_control",
    scenario: "I was detained at a roadside stop and couldn't call a lawyer for hours.",
    expectedPrimary: "charter_counsel",
    expectedResult: "nonzero_required",
    shouldInclude: ["Woods", "counsel"],
    shouldExclude: ["R v Hape"],
    expectedKeywords: ["s. 10", "counsel", "informational"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside breath-demand contexts",
        tags: ["charter", "right to counsel", "roadside detention"],
        topics: ["Charter rights", "breath demand"],
        year: 2005,
      },
    ],
  },
  {
    id: "impaired_stop_breath_demand_positive",
    scenario: "Police stopped me at a ride check, demanded a roadside breath sample, and detained me when I asked why.",
    expectedPrimary: "impaired_driving",
    expectedResult: "nonzero_required",
    shouldInclude: ["Grant", "detention"],
    shouldExclude: ["Jordan", "11(b)", "trial delay"],
    expectedKeywords: ["impaired", "breath", "detention"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Grant, 2009 SCC 32",
        title: "R v Grant",
        ratio: "Detention framework under Charter section 9 and exclusion analysis.",
        tags: ["charter", "detention", "s. 9", "roadside"],
        topics: ["detention", "charter rights"],
        year: 2009,
      },
    ],
  },
  {
    id: "impaired_refusal_lawful_demand_positive",
    scenario: "After an impaired driving stop, I refused a lawful breath demand because I wanted a lawyer first.",
    expectedPrimary: "impaired_driving",
    expectedResult: "nonzero_required",
    shouldInclude: ["Woods", "counsel"],
    shouldExclude: ["Jordan", "trial delay"],
    expectedKeywords: ["impaired", "breath", "counsel"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside breath-demand contexts.",
        tags: ["charter", "counsel", "roadside detention"],
        topics: ["counsel", "breath demand"],
        year: 2005,
      },
    ],
  },
  {
    id: "impaired_phone_search_positive",
    scenario: "During an impaired stop, officers searched my phone without a warrant after taking me to the station.",
    expectedPrimary: "impaired_driving",
    expectedResult: "nonzero_required",
    shouldInclude: ["Grant", "warrant"],
    shouldExclude: ["Jordan", "11(b)"],
    expectedKeywords: ["impaired", "search", "warrant"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Foundational Charter section 8 search and seizure framework.",
        tags: ["charter", "s. 8", "search", "warrant"],
        topics: ["search", "privacy"],
        year: 1984,
      },
    ],
  },
  {
    id: "drug_trafficking_street_sale_positive",
    scenario: "I was arrested after police said I sold fentanyl near a transit station.",
    expectedPrimary: "drug_trafficking",
    expectedResult: "nonzero_required",
    shouldInclude: ["CDSA", "trafficking"],
    shouldExclude: ["Jordan", "11(b)"],
    expectedKeywords: ["drug", "trafficking", "intent"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Smith, 2015 SCC 34",
        title: "R v Smith",
        ratio: "Trafficking analysis under the Controlled Drugs and Substances Act.",
        tags: ["cdsa", "trafficking", "drug"],
        topics: ["drug offences", "trafficking"],
        year: 2015,
      },
    ],
  },
  {
    id: "drug_trafficking_chat_logs_positive",
    scenario: "Police found chat messages about quantities and prices and charged me with trafficking cocaine.",
    expectedPrimary: "drug_trafficking",
    expectedResult: "nonzero_required",
    shouldInclude: ["CDSA", "intent"],
    shouldExclude: ["Hunter v Southam", "warrantless phone only"],
    expectedKeywords: ["trafficking", "cocaine", "intent"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Pham, 2013 SCC 15",
        title: "R v Pham",
        ratio: "Drug trafficking and proportionality in sentencing context.",
        tags: ["cdsa", "drug trafficking", "cocaine"],
        topics: ["drug offences", "sentencing"],
        year: 2013,
      },
    ],
  },
  {
    id: "sexual_assault_consent_positive",
    scenario: "I was charged after a complainant said there was no consent during sexual touching.",
    expectedPrimary: "sexual_assault",
    expectedResult: "nonzero_required",
    shouldInclude: ["consent", "sexual assault"],
    shouldExclude: ["robbery", "s. 343"],
    expectedKeywords: ["consent", "sexual", "s. 271"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Ewanchuk, [1999] 1 SCR 330",
        title: "R v Ewanchuk",
        ratio: "Affirmative consent principles in sexual assault law.",
        tags: ["sexual assault", "consent", "s. 271"],
        topics: ["consent", "sexual assault"],
        year: 1999,
      },
    ],
  },
  {
    id: "sexual_assault_mistaken_belief_positive",
    scenario: "The allegation says I ignored clear no's and now I am claiming mistaken belief in consent.",
    expectedPrimary: "sexual_assault",
    expectedResult: "nonzero_required",
    shouldInclude: ["consent", "mistaken belief"],
    shouldExclude: ["Jordan", "trial delay"],
    expectedKeywords: ["sexual assault", "consent", "s. 273"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Barton, 2019 SCC 33",
        title: "R v Barton",
        ratio: "Modern consent and sexual assault framework including legal constraints on mistaken belief.",
        tags: ["sexual assault", "consent", "s. 273"],
        topics: ["consent", "sexual assault"],
        year: 2019,
      },
    ],
  },
  {
    id: "assault_bodily_harm_broken_nose_positive",
    scenario: "I punched someone during an argument and they suffered a broken nose and stitches.",
    expectedPrimary: "assault_bodily_harm",
    expectedResult: "nonzero_required",
    shouldInclude: ["bodily harm", "s. 267"],
    shouldExclude: ["sexual assault", "trafficking"],
    expectedKeywords: ["assault", "bodily harm", "injury"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Jobidon, [1991] 2 SCR 714",
        title: "R v Jobidon",
        ratio: "Limits of consent in assault causing bodily harm.",
        tags: ["assault", "bodily harm", "consent"],
        topics: ["assault", "bodily harm"],
        year: 1991,
      },
    ],
  },
  {
    id: "assault_with_weapon_knife_positive",
    scenario: "During a fight I brandished a knife and now I am charged with assault with a weapon.",
    expectedPrimary: "assault_with_weapon",
    expectedResult: "nonzero_required",
    shouldInclude: ["weapon", "s. 267"],
    shouldExclude: ["Jordan", "11(b)"],
    expectedKeywords: ["assault", "weapon", "knife"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Felawka, [1993] 4 SCR 199",
        title: "R v Felawka",
        ratio: "Weapon possession and use in violent contexts.",
        tags: ["assault", "weapon", "knife"],
        topics: ["assault", "weapons"],
        year: 1993,
      },
    ],
  },
  {
    id: "charter_detention_only_positive",
    scenario: "Officers boxed in my car and questioned me for twenty minutes without saying I was free to leave.",
    expectedPrimary: "charter_detention",
    expectedResult: "nonzero_required",
    shouldInclude: ["Grant", "detention"],
    shouldExclude: ["Woods", "10(b)", "counsel only"],
    expectedKeywords: ["detention", "charter", "s. 9"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Grant, 2009 SCC 32",
        title: "R v Grant",
        ratio: "Defines psychological detention and section 9 analysis.",
        tags: ["charter", "detention", "s. 9"],
        topics: ["detention", "charter rights"],
        year: 2009,
      },
    ],
  },
  {
    id: "peace_bond_repeated_threats_positive",
    scenario: "My ex keeps threatening me in messages and I need to know how a peace bond application works.",
    expectedPrimary: "peace_bond",
    expectedResult: "nonzero_required",
    shouldInclude: ["peace bond", "s. 810"],
    shouldExclude: ["Jordan", "11(b)"],
    expectedKeywords: ["peace bond", "threats", "recognizance"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Budreo, [2000] OJ No 4475",
        title: "R v Budreo",
        ratio: "Charter and procedural context around peace bond-style preventive orders.",
        tags: ["peace bond", "s. 810", "preventive"],
        topics: ["peace bond", "public safety"],
        year: 2000,
      },
    ],
  },
  {
    id: "mixed_delay_plus_counsel_positive",
    scenario: "My case has taken three years and I was also denied access to counsel right after arrest.",
    expectedPrimary: "charter_counsel",
    expectedResult: "nonzero_required",
    shouldInclude: ["Woods", "counsel"],
    shouldExclude: ["Hunter v Southam", "search warrant"],
    expectedKeywords: ["delay", "11(b)", "counsel"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Sets ceilings for trial delay under Charter section 11(b).",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside and detention contexts.",
        tags: ["charter", "10(b)", "counsel"],
        topics: ["counsel", "detention"],
        year: 2005,
      },
    ],
  },
  {
    id: "robbery_force_alley_positive",
    scenario: "Two people shoved me into a wall and took my backpack and cash.",
    expectedPrimary: "robbery",
    expectedResult: "nonzero_required",
    shouldInclude: ["robbery", "force"],
    shouldExclude: ["Jordan", "11(b)"],
    expectedKeywords: ["robbery", "force", "threat"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v McCraw, [1991] 3 SCR 72",
        title: "R v McCraw",
        ratio: "Robbery analysis focuses on force or threats used to take property.",
        tags: ["robbery", "s. 343", "force", "threat"],
        topics: ["robbery", "violence"],
        year: 1991,
      },
    ],
  },
  {
    id: "theft_store_conversion_positive",
    scenario: "Store security says I concealed items and left without paying.",
    expectedPrimary: "theft",
    expectedResult: "nonzero_required",
    shouldInclude: ["theft", "s. 322"],
    shouldExclude: ["Jordan", "11(b)"],
    expectedKeywords: ["theft", "property", "dishonesty"],
    minResults: 1,
    maxResults: 3,
    landmarkMatches: [
      {
        citation: "R v Stewart, [1988] 1 SCR 963",
        title: "R v Stewart",
        ratio: "Theft requires dishonest taking or conversion of property under section 322.",
        tags: ["theft", "s. 322", "dishonesty"],
        topics: ["theft", "property"],
        year: 1988,
      },
    ],
  },
  {
    id: "impaired_minor_ticket_negative",
    scenario: "I got a speeding ticket for 5 km over and there was no detention, search, or breath demand.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Grant", "Hunter", "Woods", "Jordan"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Grant, 2009 SCC 32",
        title: "R v Grant",
        ratio: "Detention framework under Charter section 9.",
        tags: ["charter", "detention", "s. 9"],
        topics: ["detention", "charter rights"],
        year: 2009,
      },
    ],
  },
  {
    id: "simple_possession_not_trafficking_negative",
    scenario: "I had a tiny amount of cannabis for personal use and no evidence of selling.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["trafficking", "CDSA s. 5", "intent to distribute"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Smith, 2015 SCC 34",
        title: "R v Smith",
        ratio: "Drug trafficking analysis under the CDSA.",
        tags: ["cdsa", "trafficking", "drug"],
        topics: ["drug offences", "trafficking"],
        year: 2015,
      },
    ],
  },
  {
    id: "bar_fight_self_defence_negative",
    scenario: "I pushed someone away in a bar fight because they swung first and I left immediately.",
    expectedPrimary: "assault_bodily_harm",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["sexual assault", "trafficking", "Jordan"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Jobidon, [1991] 2 SCR 714",
        title: "R v Jobidon",
        ratio: "Limits of consent and violence in assault cases.",
        tags: ["assault", "bodily harm", "consent"],
        topics: ["assault", "violence"],
        year: 1991,
      },
    ],
  },
  {
    id: "detention_mislabeled_as_search_negative",
    scenario: "An officer asked me for ID briefly on the sidewalk and then let me continue walking.",
    expectedPrimary: "charter_detention",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Hunter", "search", "warrant", "Jordan"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Search and seizure framework under Charter section 8.",
        tags: ["charter", "s. 8", "search", "warrant"],
        topics: ["search", "seizure"],
        year: 1984,
      },
    ],
  },
  {
    id: "landlord_repair_dispute_negative",
    scenario: "My landlord will not fix mold and I want to file at the housing board.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Grant", "Jordan", "Hunter", "Woods"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Trial delay ceilings under Charter section 11(b).",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "workplace_harassment_policy_negative",
    scenario: "My manager is bullying me and HR has not enforced workplace policy.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["robbery", "theft", "charter", "Jordan"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v McCraw, [1991] 3 SCR 72",
        title: "R v McCraw",
        ratio: "Robbery and threat analysis under section 343.",
        tags: ["robbery", "threat", "force"],
        topics: ["robbery", "violence"],
        year: 1991,
      },
    ],
  },
  {
    id: "online_defamation_civil_negative",
    scenario: "Someone posted false statements about me online and I want a civil remedy.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["theft", "robbery", "Jordan", "Woods"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Stewart, [1988] 1 SCR 963",
        title: "R v Stewart",
        ratio: "Theft and dishonest conversion of property.",
        tags: ["theft", "property", "dishonesty"],
        topics: ["theft", "property"],
        year: 1988,
      },
    ],
  },
  {
    id: "neighbor_tree_damage_civil_negative",
    scenario: "A neighbor's tree branch damaged my fence and we are arguing about costs.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["charter", "Hunter", "Grant", "Jordan"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Grant, 2009 SCC 32",
        title: "R v Grant",
        ratio: "Detention and section 9 Charter analysis.",
        tags: ["charter", "detention", "s. 9"],
        topics: ["detention", "charter rights"],
        year: 2009,
      },
    ],
  },
  {
    id: "lost_phone_found_property_negative",
    scenario: "I lost my phone at a cafe and someone turned it in later.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["robbery", "s. 343", "force", "threat"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v McCraw, [1991] 3 SCR 72",
        title: "R v McCraw",
        ratio: "Robbery analysis focuses on threats and force.",
        tags: ["robbery", "threat", "force"],
        topics: ["robbery", "property"],
        year: 1991,
      },
    ],
  },
  {
    id: "ambulance_bill_dispute_negative",
    scenario: "I disagree with an ambulance bill and want to challenge the charge.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Jordan", "Hunter", "Woods", "Grant"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "Hunter v Southam Inc, [1984] 2 SCR 145",
        title: "Hunter v Southam Inc",
        ratio: "Charter section 8 search and seizure principles.",
        tags: ["charter", "search", "warrant"],
        topics: ["privacy", "search"],
        year: 1984,
      },
    ],
  },
  {
    id: "student_plagiarism_policy_negative",
    scenario: "My college flagged plagiarism and I need to appeal the academic decision.",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["theft", "robbery", "charter", "Jordan"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Jordan, 2016 SCC 27",
        title: "R v Jordan",
        ratio: "Trial delay ceilings under Charter section 11(b).",
        tags: ["charter", "11(b)", "trial delay"],
        topics: ["trial delay", "reasonable time"],
        year: 2016,
      },
    ],
  },
  {
    id: "parking_ticket_late_fee_negative",
    scenario: "I paid a parking ticket late and now there is an extra municipal fee.",
    expectedPrimary: "minor_traffic_stop",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Grant", "Hunter", "Woods", "Jordan"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R. v. Woods, 2005 SCC 42",
        title: "R. v. Woods",
        ratio: "Right to counsel in roadside detention contexts.",
        tags: ["charter", "10(b)", "counsel"],
        topics: ["counsel", "detention"],
        year: 2005,
      },
    ],
  },
  {
    id: "ambiguous_can_i_be_charged_negative",
    scenario: "Can I be charged for what happened yesterday if things got heated?",
    expectedPrimary: "general_criminal",
    expectedResult: "zero_expected",
    shouldInclude: [],
    shouldExclude: ["Jordan", "Hunter", "McCraw", "Stewart"],
    expectedKeywords: [],
    minResults: 0,
    maxResults: 0,
    landmarkMatches: [
      {
        citation: "R v Stewart, [1988] 1 SCR 963",
        title: "R v Stewart",
        ratio: "Theft and dishonest conversion principles.",
        tags: ["theft", "s. 322", "dishonesty"],
        topics: ["theft", "property"],
        year: 1988,
      },
    ],
  },
];